/// Regression coverage for the finite shield pool and its position before wound generation.
/datum/unit_test/shield_potion_damage/Run()
	var/mob/living/carbon/human/consistent/victim = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/bodypart/chest = victim.get_bodypart(BODY_ZONE_CHEST)
	TEST_ASSERT_EQUAL(victim.add_potion_shield(25, 50), 25, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(victim.add_potion_shield(25, 50), 25, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(victim.add_potion_shield(25, 50), 0, "Minis must stop at 50.")
	TEST_ASSERT_EQUAL(victim.add_potion_shield(50), 50, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(victim.get_potion_shield(), 100, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(victim.add_potion_shield(25, 50), 0, "A mini must not lower a pool over 50.")
	var/datum/status_effect/potion_shield/effect = victim.has_status_effect(/datum/status_effect/potion_shield)
	TEST_ASSERT_NOTNULL(effect.linked_alert, "A shield must show its owner a HUD alert.")
	TEST_ASSERT_EQUAL(effect.linked_alert.icon_state, "m_shield", "Shield potion regression check failed.")
	victim.apply_damage(80, BRUTE, chest, blocked = 50, wound_bonus = CANT_WOUND)
	TEST_ASSERT_EQUAL(victim.get_potion_shield(), 60, "Armor must mitigate before shield absorption.")
	TEST_ASSERT_EQUAL(victim.getBruteLoss(), 0, "Shield potion regression check failed.")
	// High wound chance must still do nothing when all damage is shielded.
	victim.apply_damage(50, BRUTE, chest, wound_bonus = 1000, sharpness = SHARP_EDGED)
	TEST_ASSERT_EQUAL(victim.get_potion_shield(), 10, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(length(chest.wounds), 0, "Absorbed damage must not generate wounds.")
	victim.apply_damage(25, BURN, chest, wound_bonus = CANT_WOUND)
	TEST_ASSERT_EQUAL(victim.get_potion_shield(), 0, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(round(victim.getFireLoss(), 0.1), 15, "Only overflow may reach the body.")
	TEST_ASSERT_NULL(victim.has_status_effect(/datum/status_effect/potion_shield), "Broken shields must remove their effect and HUD.")

/// Mixed damage must share shield proportionally; healing and nonphysical damage bypass it.
/datum/unit_test/shield_potion_mixed/Run()
	var/mob/living/carbon/human/consistent/victim = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/bodypart/chest = victim.get_bodypart(BODY_ZONE_CHEST)
	victim.add_potion_shield(20)
	chest.receive_damage(30, 10, wound_bonus = CANT_WOUND)
	TEST_ASSERT_EQUAL(victim.getBruteLoss(), 15, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(victim.getFireLoss(), 5, "Shield potion regression check failed.")
	victim.add_potion_shield(50)
	victim.adjustBruteLoss(-5)
	victim.adjustFireLoss(-5)
	victim.apply_damage(5, TOX)
	victim.apply_damage(5, OXY)
	victim.apply_damage(5, STAMINA)
	TEST_ASSERT_EQUAL(victim.get_potion_shield(), 50, "Healing, toxins, oxygen and stamina must not consume shield.")
	TEST_ASSERT_EQUAL(victim.getBruteLoss(), 10, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(victim.getFireLoss(), 0, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(victim.getToxLoss(), 5, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(victim.getOxyLoss(), 5, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(victim.getStaminaLoss(), 5, "Shield potion regression check failed.")
	chest.receive_damage(5, forced = TRUE, wound_bonus = CANT_WOUND)
	TEST_ASSERT_EQUAL(victim.get_potion_shield(), 50, "Forced damage must bypass shield.")
	TEST_ASSERT_EQUAL(victim.getBruteLoss(), 15, "Shield potion regression check failed.")
	ADD_TRAIT(victim, TRAIT_GODMODE, TRAIT_SOURCE_UNIT_TESTS)
	victim.apply_damage(20, BRUTE, chest)
	TEST_ASSERT_EQUAL(victim.get_potion_shield(), 50, "Godmode must not drain shield.")
	REMOVE_TRAIT(victim, TRAIT_GODMODE, TRAIT_SOURCE_UNIT_TESTS)
	victim.death()
	TEST_ASSERT_EQUAL(victim.get_potion_shield(), 0, "Shield must be cleared on death.")

/// Shielded spread damage must not be retried against every successive limb.
/datum/unit_test/shield_potion_spread/Run()
	var/mob/living/carbon/human/consistent/victim = allocate(/mob/living/carbon/human/consistent)
	victim.add_potion_shield(100)
	victim.take_overall_damage(brute = 60)
	TEST_ASSERT_EQUAL(victim.get_potion_shield(), 40, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(victim.getBruteLoss(), 0, "Shield potion regression check failed.")
	victim.take_overall_damage(brute = 60)
	TEST_ASSERT_EQUAL(victim.get_potion_shield(), 0, "Shield potion regression check failed.")
	TEST_ASSERT_EQUAL(round(victim.getBruteLoss(), 0.1), 20, "Shield potion regression check failed.")

/// Exercise the actual do_after path, including a hit entirely absorbed by a shield.
/datum/unit_test/shield_potion_drinking/Run()
	var/mob/living/carbon/human/consistent/drinker = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/shield_potion/small/potion = allocate(/obj/item/shield_potion/small)
	potion.drink_time = 0.5 SECONDS
	drinker.put_in_active_hand(potion, forced = TRUE)
	drinker.add_potion_shield(25, 50)
	INVOKE_ASYNC(potion, TYPE_PROC_REF(/obj/item/shield_potion, attack_self), drinker)
	sleep(0.1 SECONDS)
	drinker.apply_damage(5, BRUTE, BODY_ZONE_CHEST, wound_bonus = CANT_WOUND)
	sleep(0.6 SECONDS)
	TEST_ASSERT(!QDELETED(potion), "An interrupted potion must not be consumed.")
	TEST_ASSERT_EQUAL(drinker.get_potion_shield(), 20, "An absorbed hit must cancel drinking.")
	TEST_ASSERT_NULL(potion.drinker, "An interrupted drink must release the drinker.")
	TEST_ASSERT_NULL(potion.drink_listeners, "An interrupted drink must release audio listeners.")
	potion.attack_self(drinker)
	TEST_ASSERT(QDELETED(potion), "A completed drink must consume the item.")
	TEST_ASSERT_EQUAL(drinker.get_potion_shield(), 45, "Shield potion regression check failed.")

/// The precursor temperature gate must stay narrow.
/datum/unit_test/shield_potion_recipe/Run()
	var/datum/chemical_reaction/shield_concentrate/recipe = allocate(/datum/chemical_reaction/shield_concentrate)
	var/obj/item/reagent_containers/cup/beaker = allocate(/obj/item/reagent_containers/cup/beaker)
	beaker.reagents.chem_temp = 269
	TEST_ASSERT(!recipe.pre_reaction_other_checks(beaker.reagents), "Shield potion regression check failed.")
	beaker.reagents.chem_temp = 275
	TEST_ASSERT(recipe.pre_reaction_other_checks(beaker.reagents), "Shield potion regression check failed.")
	beaker.reagents.chem_temp = 281
	TEST_ASSERT(!recipe.pre_reaction_other_checks(beaker.reagents), "Shield potion regression check failed.")
